# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build config
      run: go build -v ./config

    - name: Install xmllint
      run: sudo apt-get install -y libusb-1.0-0

    - name: Build lib
      run: go build -v ./lib

    - name: Build cli
      run: go build -v ./cli

    - name: Build ui
      run: go build -v ./ui
