# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build config
      run: go build -v ./config

    - name: Install libudev
      run: sudo apt-get install -y libudev-dev

    - name: Build lib
      run: go build -v ./lib

    - name: Build cli
      run: go build -o lcli -v ./lcli

    - name: Install X dependencies
      run: sudo apt-get install -y libgl1-mesa-dev xorg-dev

    - name: Build ui
      run: go build -o lcui -v ./lcui

    - name: Run Unit Tests
      run:  go test -cover -coverprofile=coverage.out -v ./config ./lib ./lcli/cmd

    - name: Coveage report
      run: go tool cover -func=coverage.out
